import { useState, useEffect, useCallback, useMemo, useRef, FormEvent } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
import ReactMarkdown from 'react-markdown';
import DOMPurify from 'dompurify';
import { List, Clock, Reply, Trash2 } from 'lucide-react';
import { useAuth } from '../../src/context/AuthContext';
import { useAuthModal } from '../../src/context/AuthModalContext';
import { BlogPost, BlogComment } from '../../src/types/blog';
import {
  getBlogPostById,
  getBlogPosts,
  resolveBlogImageUrl,
  blogTitle,
  blogDescription,
  blogContent,
  estimateReadingMinutes,
  isSuccessStory,
  getBlogComments,
  createBlogComment,
  deleteBlogComment,
} from '../../src/services/blogService';
import SocialShareButtons from '../../src/components/shared/SocialShareButtons';
import Lightbox, { LightboxImage } from '../../src/components/shared/Lightbox';
import { onImageErrorFallback } from '../../src/utils/imageFallback';
import SiteHeader from '../../src/components/layout/SiteHeader';

const dict = {
  ka: {
    loading: 'იტვირთება…',
    notFound: 'სტატია ვერ მოიძებნა.',
    back: '← ბლოგზე დაბრუნება',
    by: 'ავტორი',
    minRead: (n: number) => `${n} წთ კითხვა`,
    toc: 'სარჩევი',
    related: 'დაკავშირებული სტატიები',
    comments: 'კომენტარები',
    signInToComment: 'კომენტარის დასატოვებლად გაიარეთ ავტორიზაცია',
    commentPlaceholder: 'დაწერეთ თქვენი კომენტარი…',
    post: 'გამოქვეყნება',
    posting: 'იგზავნება…',
    reply: 'პასუხი',
    replyPlaceholder: 'დაწერეთ პასუხი…',
    noComments: 'ჯერ არავის დაუტოვებია კომენტარი. იყავით პირველი!',
    commentError: 'კომენტარის გაგზავნა ვერ მოხერხდა. სცადეთ თავიდან.',
    delete: 'წაშლა',
  },
  en: {
    loading: 'Loading…',
    notFound: 'Article not found.',
    back: '← Back to blog',
    by: 'By',
    minRead: (n: number) => `${n} min read`,
    toc: 'Table of Contents',
    related: 'Related Articles',
    comments: 'Comments',
    signInToComment: 'Please sign in to leave a comment',
    commentPlaceholder: 'Write your comment…',
    post: 'Post',
    posting: 'Posting…',
    reply: 'Reply',
    replyPlaceholder: 'Write a reply…',
    noComments: 'No comments yet. Be the first to share your thoughts!',
    commentError: 'Failed to post comment. Please try again.',
    delete: 'Delete',
  },
};

// No rehype-slug plugin in this project — headings get stable anchor ids by
// deriving them from the raw markdown source (extractHeadings) and
// re-deriving them in the exact same document order while ReactMarkdown
// renders (headingIndexRef below), so both passes agree.
function slugifyHeading(input: string): string {
  const base = input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/[\s-]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base || 'section';
}

interface Heading {
  id: string;
  text: string;
  level: number;
}

function extractHeadings(markdown: string): Heading[] {
  const seen = new Map<string, number>();
  const headings: Heading[] = [];
  for (const rawLine of markdown.split('\n')) {
    const match = /^(#{2,3})\s+(.+)$/.exec(rawLine.trim());
    if (!match) continue;
    const level = match[1].length;
    const text = match[2].trim();
    let id = slugifyHeading(text);
    const count = seen.get(id) ?? 0;
    seen.set(id, count + 1);
    if (count > 0) id = `${id}-${count}`;
    headings.push({ id, text, level });
  }
  return headings;
}

interface ContentImage {
  url: string;
  alt: string;
}

// Extracted straight from the markdown source (not the rendered DOM) — same
// "parse the raw string, then re-derive in the same order while
// ReactMarkdown renders" approach as extractHeadings, via contentImageIndexRef.
function extractContentImages(markdown: string): ContentImage[] {
  const images: ContentImage[] = [];
  const regex = /!\[([^\]]*)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(markdown))) {
    images.push({ alt: match[1], url: match[2] });
  }
  return images;
}

// Human-authored posts (RichTextEditor, /admin/blog) are Markdown; posts
// generated by the CDC AI agent (services/aiAgentService.ts) are HTML —
// this heuristic tells the two apart so the right renderer runs. AI content
// always starts with an opening tag (<h2>/<p>/...) by construction; Markdown
// content (headings, bold, plain prose) never does.
function isHtmlContent(content: string): boolean {
  return /^\s*<[a-z][\s\S]*>/i.test(content);
}

interface HtmlArticle {
  sanitizedHtml: string;
  headings: Heading[];
  images: ContentImage[];
}

// Parses AI-generated HTML content with the real browser DOM (client-side
// only — this only ever runs after the post has loaded), assigns the same
// heading-id scheme extractHeadings/slugifyHeading uses (so the table of
// contents and #anchor links work identically to the Markdown path),
// resolves image URLs, forces rel="noopener noreferrer" on target="_blank"
// links, and finally sanitizes with DOMPurify before it's ever handed to
// dangerouslySetInnerHTML — this content originates from an LLM (and,
// indirectly, admin-supplied topic keywords), so it's treated as untrusted
// input, never executed/rendered without sanitization.
function renderHtmlArticle(html: string, resolveImageUrl: (url: string) => string): HtmlArticle {
  if (typeof window === 'undefined' || typeof DOMParser === 'undefined') {
    return { sanitizedHtml: '', headings: [], images: [] };
  }

  const doc = new DOMParser().parseFromString(html, 'text/html');

  const headings: Heading[] = [];
  const seen = new Map<string, number>();
  doc.querySelectorAll('h2, h3').forEach((el) => {
    const level = el.tagName === 'H2' ? 2 : 3;
    const text = el.textContent?.trim() ?? '';
    let id = slugifyHeading(text);
    const count = seen.get(id) ?? 0;
    seen.set(id, count + 1);
    if (count > 0) id = `${id}-${count}`;
    el.setAttribute('id', id);
    headings.push({ id, text, level });
  });

  const images: ContentImage[] = [];
  doc.querySelectorAll('img').forEach((img) => {
    const src = img.getAttribute('src');
    if (!src) return;
    const resolved = resolveImageUrl(src);
    img.setAttribute('src', resolved);
    images.push({ url: resolved, alt: img.getAttribute('alt') ?? '' });
  });

  doc.querySelectorAll('a[target="_blank"]').forEach((a) => {
    a.setAttribute('rel', 'noopener noreferrer');
  });

  const sanitizedHtml = DOMPurify.sanitize(doc.body.innerHTML, {
    ALLOWED_TAGS: ['h2', 'h3', 'p', 'ul', 'ol', 'li', 'strong', 'em', 'b', 'i', 'a', 'img', 'blockquote', 'code', 'pre', 'br'],
    ALLOWED_ATTR: ['href', 'target', 'rel', 'src', 'alt', 'id'],
  });

  return { sanitizedHtml, headings, images };
}

interface CommentThreadProps {
  comment: BlogComment;
  replies: BlogComment[];
  lang: 'ka' | 'en';
  t: (typeof dict)['ka'];
  canModerate: boolean;
  onReply: (parentId: string) => void;
  onDelete: (commentId: string) => void;
  replyingTo: string | null;
  replyContent: string;
  onReplyContentChange: (value: string) => void;
  onSubmitReply: (e: FormEvent, parentId: string) => void;
  submitting: boolean;
}

function CommentHeader({
  comment,
  lang,
  t,
  canModerate,
  onDelete,
}: {
  comment: BlogComment;
  lang: 'ka' | 'en';
  t: (typeof dict)['ka'];
  canModerate: boolean;
  onDelete: (commentId: string) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-2">
      <div className="flex items-center gap-2">
        {comment.author.avatarUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={resolveBlogImageUrl(comment.author.avatarUrl)} alt={comment.author.name} onError={onImageErrorFallback} className="w-7 h-7 rounded-full object-cover" />
        ) : (
          <div className="w-7 h-7 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-600 flex items-center justify-center text-white text-[10px] font-black">
            {comment.author.name.charAt(0).toUpperCase()}
          </div>
        )}
        <p className="text-sm font-bold text-white">{comment.author.name}</p>
        <span className="text-xs text-slate-500">{new Date(comment.createdAt).toLocaleDateString(lang === 'ka' ? 'ka-GE' : 'en-US')}</span>
      </div>
      {canModerate && (
        <button
          type="button"
          onClick={() => onDelete(comment.id)}
          aria-label={t.delete}
          title={t.delete}
          className="text-slate-600 hover:text-red-400 bg-transparent cursor-pointer"
        >
          <Trash2 size={14} />
        </button>
      )}
    </div>
  );
}

function CommentThread({
  comment,
  replies,
  lang,
  t,
  canModerate,
  onReply,
  onDelete,
  replyingTo,
  replyContent,
  onReplyContentChange,
  onSubmitReply,
  submitting,
}: CommentThreadProps) {
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm p-4 transition-colors hover:border-cyan-400/30">
      <CommentHeader comment={comment} lang={lang} t={t} canModerate={canModerate} onDelete={onDelete} />
      <p className="text-sm text-slate-300 mt-2 whitespace-pre-wrap break-words">{comment.content}</p>
      <button
        type="button"
        onClick={() => onReply(comment.id)}
        className="flex items-center gap-1 text-xs font-bold text-cyan-400 mt-3 bg-transparent cursor-pointer hover:text-cyan-300"
      >
        <Reply size={12} /> {t.reply}
      </button>

      {replyingTo === comment.id && (
        <form onSubmit={(e) => onSubmitReply(e, comment.id)} className="mt-3">
          <textarea
            rows={2}
            value={replyContent}
            onChange={(e) => onReplyContentChange(e.target.value)}
            placeholder={t.replyPlaceholder}
            className="w-full rounded-lg border border-slate-700 bg-slate-950/60 px-3 py-2 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/60"
          />
          <div className="flex justify-end mt-2">
            <button
              type="submit"
              disabled={submitting}
              className="text-xs font-bold text-white bg-cyan-600 px-3.5 py-1.5 rounded-lg hover:bg-cyan-500 disabled:opacity-60"
            >
              {submitting ? t.posting : t.post}
            </button>
          </div>
        </form>
      )}

      {replies.length > 0 && (
        <div className="mt-4 pl-5 border-l border-slate-800 space-y-3">
          {replies.map((reply) => (
            <div key={reply.id}>
              <CommentHeader comment={reply} lang={lang} t={t} canModerate={canModerate} onDelete={onDelete} />
              <p className="text-sm text-slate-300 mt-2 whitespace-pre-wrap break-words">{reply.content}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function BlogPostPage() {
  const router = useRouter();
  const lang = router.locale === 'en' ? 'en' : 'ka';
  const t = dict[lang];
  const { user, isAuthenticated } = useAuth();
  const { openAuthModal } = useAuthModal();
  const slug = typeof router.query.slug === 'string' ? router.query.slug : null;

  const [post, setPost] = useState<BlogPost | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [relatedPosts, setRelatedPosts] = useState<BlogPost[]>([]);
  const [comments, setComments] = useState<BlogComment[]>([]);
  const [newComment, setNewComment] = useState('');
  const [submittingComment, setSubmittingComment] = useState(false);
  const [commentError, setCommentError] = useState<string | null>(null);
  const [replyingTo, setReplyingTo] = useState<string | null>(null);
  const [replyContent, setReplyContent] = useState('');

  const canModerateComments = user?.adminRole === 'SUPER_ADMIN' || user?.adminRole === 'MANAGER';

  const load = useCallback(async () => {
    if (!slug) return;
    setLoading(true);
    setNotFound(false);
    try {
      const data = await getBlogPostById(slug);
      if (!data.published) {
        setNotFound(true);
      } else {
        setPost(data);
      }
    } catch {
      setNotFound(true);
    } finally {
      setLoading(false);
    }
  }, [slug]);

  useEffect(() => {
    load();
  }, [load]);

  useEffect(() => {
    if (!post) {
      setRelatedPosts([]);
      return;
    }
    getBlogPosts(post.category)
      .then((data) => setRelatedPosts(data.filter((p) => p.published && p.id !== post.id).slice(0, 3)))
      .catch(() => setRelatedPosts([]));
  }, [post]);

  const loadComments = useCallback(async () => {
    if (!slug) return;
    try {
      setComments(await getBlogComments(slug));
    } catch {
      // Non-fatal — the article itself already loaded; comments just stay empty.
    }
  }, [slug]);

  useEffect(() => {
    loadComments();
  }, [loadComments]);

  const content = post ? blogContent(post, lang) : '';
  // Human-authored posts (Markdown, via RichTextEditor) and CDC AI agent
  // posts (HTML, via aiAgentService.ts) need different rendering pipelines
  // — see isHtmlContent()/renderHtmlArticle() above. Both useMemo branches
  // are always computed (Rules of Hooks) but only one is ever actually used.
  const isHtml = useMemo(() => isHtmlContent(content), [content]);

  const markdownHeadings = useMemo(() => (isHtml ? [] : extractHeadings(content)), [content, isHtml]);
  const htmlArticle = useMemo(
    () => (isHtml ? renderHtmlArticle(content, resolveBlogImageUrl) : null),
    [content, isHtml]
  );
  const headings = isHtml ? htmlArticle?.headings ?? [] : markdownHeadings;
  const headingIndexRef = useRef(0);
  headingIndexRef.current = 0;

  const markdownContentImages = useMemo(() => (isHtml ? [] : extractContentImages(content)), [content, isHtml]);
  const contentImages = isHtml ? htmlArticle?.images ?? [] : markdownContentImages;
  // Cover image (when present) occupies index 0; content images follow in
  // document order — contentImageIndexRef mirrors headingIndexRef's trick of
  // re-deriving the same order while ReactMarkdown renders (Markdown path
  // only; the HTML path resolves image URLs up front in renderHtmlArticle
  // and matches by URL instead — see handleHtmlContentClick).
  const galleryImages = useMemo<LightboxImage[]>(() => {
    const items: LightboxImage[] = [];
    if (post?.imageUrl) items.push({ url: resolveBlogImageUrl(post.imageUrl), alt: blogTitle(post, lang) });
    for (const img of contentImages) items.push({ url: resolveBlogImageUrl(img.url), alt: img.alt });
    return items;
  }, [post, contentImages, lang]);
  const contentImageIndexRef = useRef(0);
  contentImageIndexRef.current = post?.imageUrl ? 1 : 0;
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);

  // Raw HTML content isn't part of the React tree (it's injected via
  // dangerouslySetInnerHTML), so lightbox clicks on its <img> elements are
  // handled via delegation on the wrapper instead of a per-element onClick.
  const handleHtmlContentClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const target = e.target as HTMLElement;
    if (target.tagName !== 'IMG') return;
    const src = (target as HTMLImageElement).src;
    const idx = galleryImages.findIndex((img) => img.url === src);
    if (idx >= 0) setLightboxIndex(idx);
  };

  const markdownComponents = useMemo(
    () => ({
      h2: (props: React.ComponentPropsWithoutRef<'h2'>) => {
        const heading = headings[headingIndexRef.current];
        headingIndexRef.current += 1;
        return <h2 id={heading?.id} className="scroll-mt-24" {...props} />;
      },
      h3: (props: React.ComponentPropsWithoutRef<'h3'>) => {
        const heading = headings[headingIndexRef.current];
        headingIndexRef.current += 1;
        return <h3 id={heading?.id} className="scroll-mt-24" {...props} />;
      },
      a: (props: React.ComponentPropsWithoutRef<'a'>) => <a target="_blank" rel="noopener noreferrer" {...props} />,
      img: (props: React.ComponentPropsWithoutRef<'img'>) => {
        const idx = contentImageIndexRef.current;
        contentImageIndexRef.current += 1;
        return (
          // eslint-disable-next-line @next/next/no-img-element, jsx-a11y/alt-text
          <img
            {...props}
            src={props.src ? resolveBlogImageUrl(props.src) : props.src}
            onError={onImageErrorFallback}
            onClick={() => setLightboxIndex(idx)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                setLightboxIndex(idx);
              }
            }}
            role="button"
            tabIndex={0}
            className="w-full rounded-xl my-5 cursor-zoom-in"
          />
        );
      },
    }),
    [headings]
  );

  const handleSubmitComment = async (e: FormEvent) => {
    e.preventDefault();
    if (!slug) return;
    if (!isAuthenticated) {
      openAuthModal({ message: { ka: dict.ka.signInToComment, en: dict.en.signInToComment } });
      return;
    }
    if (newComment.trim().length < 1) return;
    setCommentError(null);
    setSubmittingComment(true);
    try {
      const created = await createBlogComment(slug, { content: newComment.trim() });
      setComments((prev) => [created, ...prev]);
      setNewComment('');
    } catch {
      setCommentError(t.commentError);
    } finally {
      setSubmittingComment(false);
    }
  };

  const handleSubmitReply = async (e: FormEvent, parentId: string) => {
    e.preventDefault();
    if (!slug) return;
    if (!isAuthenticated) {
      openAuthModal({ message: { ka: dict.ka.signInToComment, en: dict.en.signInToComment } });
      return;
    }
    if (replyContent.trim().length < 1) return;
    setSubmittingComment(true);
    try {
      const created = await createBlogComment(slug, { content: replyContent.trim(), parentId });
      setComments((prev) => [...prev, created]);
      setReplyContent('');
      setReplyingTo(null);
    } catch {
      setCommentError(t.commentError);
    } finally {
      setSubmittingComment(false);
    }
  };

  const handleDeleteComment = async (commentId: string) => {
    const previous = comments;
    setComments((prev) => prev.filter((c) => c.id !== commentId && c.parentId !== commentId));
    try {
      await deleteBlogComment(commentId);
    } catch {
      setComments(previous);
      setCommentError(t.commentError);
    }
  };

  const topLevelComments = comments.filter((c) => !c.parentId);
  const repliesByParent = useMemo(() => {
    const map = new Map<string, BlogComment[]>();
    for (const c of comments) {
      if (!c.parentId) continue;
      const list = map.get(c.parentId) ?? [];
      list.push(c);
      map.set(c.parentId, list);
    }
    return map;
  }, [comments]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-400 text-sm flex flex-col">
        <SiteHeader />
        <div className="flex-1 flex items-center justify-center">{t.loading}</div>
      </div>
    );
  }
  if (notFound || !post) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-300 text-sm flex flex-col">
        <SiteHeader />
        <div className="flex-1 flex flex-col items-center justify-center gap-4">
          <p>{t.notFound}</p>
          <Link href="/blog" className="text-cyan-400 hover:underline">
            {t.back}
          </Link>
        </div>
      </div>
    );
  }

  const title = blogTitle(post, lang);
  const description = blogDescription(post, lang);
  const ogImage = post.imageUrl ? resolveBlogImageUrl(post.imageUrl) : undefined;
  const readingMinutes = estimateReadingMinutes(content);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <Head>
        <title>{`${title} | CDC Blog`}</title>
        <meta name="description" content={description} />
        <meta property="og:type" content="article" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        {ogImage && <meta property="og:image" content={ogImage} />}
        <meta name="twitter:card" content={ogImage ? 'summary_large_image' : 'summary'} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        {ogImage && <meta name="twitter:image" content={ogImage} />}
      </Head>
      <SiteHeader />
      <div className="max-w-6xl mx-auto px-6 py-16">
        <Link href="/blog" className="text-sm text-slate-400 hover:text-white no-underline">
          {t.back}
        </Link>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-12 mt-6">
          <div className="max-w-2xl">
            <div className="flex flex-wrap gap-2">
              <span className="text-[10px] font-black uppercase tracking-widest px-3 py-1.5 rounded-md border text-cyan-300 bg-cyan-500/10 border-cyan-500/20">
                {post.category}
              </span>
              {isSuccessStory(post) && (
                <span className="text-[10px] font-black uppercase tracking-widest px-3 py-1.5 rounded-md border text-amber-300 bg-amber-500/10 border-amber-500/20">
                  {lang === 'ka' ? '🎓 კურსდამთავრებული' : '🎓 Graduate Success'}
                </span>
              )}
            </div>
            <h1 className="text-3xl md:text-4xl font-black mt-4 mb-4">{title}</h1>

            <div className="flex flex-wrap items-center gap-3 mb-8">
              {post.author.avatarUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={resolveBlogImageUrl(post.author.avatarUrl)} alt={post.author.name} onError={onImageErrorFallback} className="w-9 h-9 rounded-full object-cover" />
              ) : (
                <div className="w-9 h-9 rounded-full bg-gradient-to-tr from-cyan-500 to-purple-600 flex items-center justify-center text-white text-xs font-black">
                  {post.author.name.charAt(0).toUpperCase()}
                </div>
              )}
              <div className="text-xs text-slate-500 leading-tight">
                <p className="font-bold text-slate-300">{t.by} {post.author.name}</p>
                <p className="flex items-center gap-2">
                  {new Date(post.createdAt).toLocaleDateString(lang === 'ka' ? 'ka-GE' : 'en-US')}
                  <span className="flex items-center gap-1">
                    <Clock size={11} /> {t.minRead(readingMinutes)}
                  </span>
                </p>
              </div>
              <div className="ml-auto">
                <SocialShareButtons title={title} lang={lang} variant="dark" />
              </div>
            </div>

            {post.imageUrl && (
              <button
                type="button"
                onClick={() => setLightboxIndex(0)}
                aria-label={title}
                className="block w-full mb-8 p-0 border-0 bg-transparent cursor-zoom-in"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={resolveBlogImageUrl(post.imageUrl)} alt={title} onError={onImageErrorFallback} className="w-full rounded-2xl object-cover max-h-96" />
              </button>
            )}

            {headings.length > 0 && (
              <div className="lg:hidden rounded-xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm p-4 transition-colors hover:border-cyan-400/30 mb-8">
                <p className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-400 mb-3">
                  <List size={14} /> {t.toc}
                </p>
                <ul className="space-y-1.5">
                  {headings.map((h) => (
                    <li key={h.id} className={h.level === 3 ? 'pl-3' : ''}>
                      <a href={`#${h.id}`} className="text-sm text-cyan-400 hover:underline no-underline">
                        {h.text}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="blog-article-content rounded-3xl border border-slate-800/70 bg-gradient-to-b from-slate-900/50 to-slate-900/10 backdrop-blur-sm px-5 py-7 sm:px-10 sm:py-10">
              {isHtml ? (
                <div dangerouslySetInnerHTML={{ __html: htmlArticle?.sanitizedHtml ?? '' }} onClick={handleHtmlContentClick} />
              ) : (
                <ReactMarkdown components={markdownComponents}>{content}</ReactMarkdown>
              )}
            </div>

            <style jsx>{`
              .blog-article-content {
                font-size: 1.0625rem;
                line-height: 1.85;
                color: #cbd5e1;
              }
              .blog-article-content :global(h2) {
                font-size: 1.5rem;
                font-weight: 900;
                color: #ffffff;
                letter-spacing: -0.01em;
                margin: 2.75rem 0 1rem;
                scroll-margin-top: 6rem;
              }
              .blog-article-content :global(h2:first-child) {
                margin-top: 0;
              }
              .blog-article-content :global(h3) {
                font-size: 1.2rem;
                font-weight: 800;
                color: #ffffff;
                margin: 2rem 0 0.75rem;
                scroll-margin-top: 6rem;
              }
              .blog-article-content :global(p) {
                margin: 0 0 1.35rem;
              }
              .blog-article-content :global(ul),
              .blog-article-content :global(ol) {
                margin: 0 0 1.5rem;
                padding-left: 1.35rem;
                display: flex;
                flex-direction: column;
                gap: 0.55rem;
              }
              .blog-article-content :global(ul) {
                list-style: disc;
              }
              .blog-article-content :global(ol) {
                list-style: decimal;
              }
              .blog-article-content :global(li::marker) {
                color: #22d3ee;
              }
              .blog-article-content :global(strong) {
                color: #ffffff;
                font-weight: 700;
              }
              .blog-article-content :global(em) {
                color: #e2e8f0;
              }
              .blog-article-content :global(a) {
                color: #22d3ee;
                text-decoration: underline;
                text-underline-offset: 3px;
                font-weight: 600;
              }
              .blog-article-content :global(a:hover) {
                color: #67e8f9;
              }
              .blog-article-content :global(blockquote) {
                border-left: 3px solid rgba(34, 211, 238, 0.5);
                padding: 0.25rem 0 0.25rem 1.35rem;
                margin: 1.85rem 0;
                font-style: italic;
                color: #94a3b8;
              }
              .blog-article-content :global(code) {
                background: rgba(30, 41, 59, 0.9);
                color: #67e8f9;
                padding: 0.2rem 0.45rem;
                border-radius: 0.4rem;
                font-size: 0.85em;
                font-family: ui-monospace, 'SF Mono', Menlo, monospace;
              }
              .blog-article-content :global(pre) {
                background: #0b1220;
                border: 1px solid #1e293b;
                border-radius: 0.9rem;
                padding: 1.25rem 1.5rem;
                overflow-x: auto;
                margin: 1.75rem 0;
              }
              .blog-article-content :global(pre code) {
                background: none;
                padding: 0;
              }
              .blog-article-content :global(img) {
                width: 100%;
                border-radius: 1.1rem;
                margin: 1.75rem 0;
                cursor: zoom-in;
              }
            `}</style>

            {relatedPosts.length > 0 && (
              <div className="mt-16">
                <h2 className="text-xl font-black mb-6">{t.related}</h2>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {relatedPosts.map((related) => (
                    <Link
                      key={related.id}
                      href={`/blog/${related.slug}`}
                      className="rounded-xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm p-4 no-underline text-current transition-colors hover:border-cyan-400/50"
                    >
                      <p className="text-sm font-bold text-white line-clamp-2 mb-1">{blogTitle(related, lang)}</p>
                      <p className="text-xs text-slate-500 line-clamp-2">{blogDescription(related, lang)}</p>
                    </Link>
                  ))}
                </div>
              </div>
            )}

            <div className="mt-16">
              <h2 className="text-xl font-black mb-6">
                {t.comments} {comments.length > 0 && <span className="text-slate-500">({comments.length})</span>}
              </h2>

              <form onSubmit={handleSubmitComment} className="mb-8">
                {commentError && <p className="text-xs text-red-400 mb-2">{commentError}</p>}
                <textarea
                  rows={3}
                  value={newComment}
                  onChange={(e) => setNewComment(e.target.value)}
                  placeholder={t.commentPlaceholder}
                  className="w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3.5 py-2.5 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/60"
                />
                <div className="flex justify-end mt-2">
                  <button
                    type="submit"
                    disabled={submittingComment}
                    className="text-sm font-bold text-white bg-cyan-600 px-4 py-2 rounded-lg hover:bg-cyan-500 disabled:opacity-60"
                  >
                    {submittingComment ? t.posting : t.post}
                  </button>
                </div>
              </form>

              {topLevelComments.length === 0 ? (
                <p className="text-sm text-slate-500">{t.noComments}</p>
              ) : (
                <div className="space-y-4">
                  {topLevelComments.map((comment) => (
                    <CommentThread
                      key={comment.id}
                      comment={comment}
                      replies={repliesByParent.get(comment.id) ?? []}
                      lang={lang}
                      t={t}
                      canModerate={canModerateComments}
                      onReply={(parentId) => {
                        setReplyingTo((current) => (current === parentId ? null : parentId));
                        setReplyContent('');
                      }}
                      onDelete={handleDeleteComment}
                      replyingTo={replyingTo}
                      replyContent={replyContent}
                      onReplyContentChange={setReplyContent}
                      onSubmitReply={handleSubmitReply}
                      submitting={submittingComment}
                    />
                  ))}
                </div>
              )}
            </div>
          </div>

          {headings.length > 0 && (
            <aside className="hidden lg:block">
              <div className="sticky top-8 rounded-xl border border-slate-800 bg-slate-900/60 backdrop-blur-sm p-4 transition-colors hover:border-cyan-400/30">
                <p className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-400 mb-3">
                  <List size={14} /> {t.toc}
                </p>
                <ul className="space-y-1.5">
                  {headings.map((h) => (
                    <li key={h.id} className={h.level === 3 ? 'pl-3' : ''}>
                      <a href={`#${h.id}`} className="text-sm text-slate-400 hover:text-cyan-400 no-underline">
                        {h.text}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            </aside>
          )}
        </div>
      </div>

      <Lightbox
        images={galleryImages}
        index={lightboxIndex}
        onClose={() => setLightboxIndex(null)}
        onIndexChange={setLightboxIndex}
      />
    </div>
  );
}
