// Shared between the admin RichTextEditor preview and the public blog page
// renderer (pages/blog/[slug].tsx) so both agree on what counts as "HTML"
// content and what's allowed through DOMPurify — one definition, no drift.
//
// Human-authored posts (RichTextEditor, /admin/blog) are Markdown; posts
// generated by the CDC AI agent (services/aiAgentService.ts) are HTML — this
// heuristic tells the two apart. AI content always starts with an opening
// tag (<h2>/<p>/...) by construction; Markdown content (headings, bold,
// plain prose) never does.
export function isHtmlContent(content: string): boolean {
  return /^\s*<[a-z][\s\S]*>/i.test(content);
}

export const HTML_CONTENT_ALLOWED_TAGS = ['h2', 'h3', 'p', 'ul', 'ol', 'li', 'strong', 'em', 'b', 'i', 'a', 'img', 'blockquote', 'code', 'pre', 'br'];
export const HTML_CONTENT_ALLOWED_ATTR = ['href', 'target', 'rel', 'src', 'alt', 'id'];
